# Generated by Django 4.2 on 2024-12-21 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0002_alter_plan_time_unit_subscription_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.AddField(
            model_name='purchase',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='subscription.plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='purchase',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscription.purchase'),
            preserve_default=False,
        ),
    ]
