# Generated by Django 4.2 on 2024-12-25 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payment_uid'),
        ('subscription', '0003_remove_purchase_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='purchase', to='payment.payment'),
        ),
    ]
