# Generated by Django 4.2 on 2025-01-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Admin'), ('author', 'Author'), ('subscriber', 'Subscriber'), ('member', 'Member')], default='member', max_length=11),
        ),
    ]
