# Generated by Django 4.2 on 2024-12-21 08:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_created_time_payment_modified_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
