# Generated by Django 4.2 on 2024-12-21 08:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
